<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="Alquds_book_store.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
  
        <div class="jumbotron">
        <h2> About Alquds Ebook STore system</h2>
        <p class="lead"></p>
        <p><a href="#" >
            </a></p>
    </div>

    <div class="row">
        
            <h2></h2>
            <p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ac mollis elit. Ut vestibulum, felis sed vestibulum fermentum, nibh nibh faucibus urna, ut rutrum mauris risus in tortor. Curabitur vel leo rhoncus, fringilla neque in, finibus sem. Aliquam vitae finibus urna. Praesent pharetra, neque nec hendrerit elementum, purus libero scelerisque nisi, id placerat ante tortor eu lacus. Phasellus consectetur in enim id tristique. Donec cursus rutrum eros, egestas eleifend leo fermentum feugiat. Vestibulum facilisis lectus consectetur bibendum pulvinar. Nunc mollis accumsan egestas. Cras in lectus quis metus finibus cursus. In congue risus non velit consectetur malesuada. Praesent vel mi ligula. Proin nunc nunc, hendrerit in aliquet eget, molestie a felis. Pellentesque volutpat a dolor eget interdum.</p>
            <p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Donec ultrices mollis ullamcorper. Quisque luctus sodales metus, eget volutpat magna sollicitudin a. Aliquam ut ipsum ipsum. Etiam eget imperdiet orci. Curabitur sodales bibendum porta. Fusce dictum tristique diam. Donec euismod eleifend turpis, eu blandit ex interdum cursus. Quisque blandit malesuada nunc non efficitur. Sed eget enim dolor. Aenean tincidunt vitae quam non ultricies. Praesent scelerisque nibh nulla, ut accumsan tellus feugiat in. In rutrum fermentum justo, eget iaculis dui. Vivamus eu elit ut neque volutpat pulvinar. Proin porttitor dictum libero, eu cursus tellus semper in. Curabitur leo nibh, maximus eget orci nec, semper iaculis sem. Cras velit nisi, ultricies quis sem in, dignissim aliquam tortor.</p>
            <p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Sed vitae sagittis sem. Quisque cursus varius elit quis mattis. Sed placerat tellus at cursus pulvinar. Aenean vel elit lacus. Morbi sagittis luctus metus nec dapibus. Duis nec viverra quam. Vivamus faucibus feugiat eleifend. Ut tincidunt nulla non lorem egestas porta. Cras suscipit quam non ipsum suscipit ullamcorper. Nam viverra, nisl scelerisque iaculis hendrerit, velit neque pharetra turpis, sed dapibus est erat non dolor.</p>
            <p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Aenean tempus ligula sed fringilla pellentesque. Vivamus pellentesque nisi non diam congue convallis. Donec consectetur lorem quis semper blandit. Vestibulum laoreet consectetur feugiat. Maecenas porttitor tellus non nisl elementum, non pretium neque lacinia. Vestibulum sit amet urna sed mauris auctor tincidunt sit amet at tellus. Sed dolor mi, placerat viverra mi non, dapibus hendrerit arcu. Curabitur sodales urna vitae erat scelerisque, eget porta magna sagittis. Ut porta malesuada faucibus. Etiam est dolor, ullamcorper ac nisl ac, egestas efficitur lacus. Curabitur vulputate risus non consequat interdum. Curabitur rhoncus, nisl ut lobortis vehicula, nibh enim scelerisque tellus, sit amet volutpat erat felis vitae sapien. Donec sodales venenatis libero, vel tincidunt lorem finibus sit amet. Cras imperdiet dui ex, sit amet sollicitudin sem sollicitudin non. Proin accumsan consequat felis at tincidunt.</p>
            <p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Ut in neque posuere, molestie arcu sit amet, pharetra tortor. Maecenas sodales euismod ante quis luctus. Quisque a tellus tempus, tincidunt lacus vel, tempor velit. Pellentesque ultrices sagittis mauris a sollicitudin. Nam cursus sit amet urna quis feugiat. Morbi nec mauris tempor odio facilisis consectetur non ac nulla. Nullam rhoncus pulvinar eros, id venenatis est ultricies eget. Pellentesque ligula odio, ornare id leo sit amet, volutpat consectetur lorem. Integer non tempor dui, scelerisque convallis sapien. Nulla non orci sed dolor euismod aliquet. Etiam sit amet neque diam. Fusce dui tellus, vulputate ac sapien tempus, imperdiet bibendum metus. Ut id orci posuere, rhoncus diam ut, rutrum turpis. Nunc et enim lectus. Sed at libero id lorem porttitor venenatis vitae nec sem.</p>
         <p>&nbsp;</p>
            
       
    </div>

</asp:Content>
